"""
PDF Compilation Module
Generates final PDF output from healed geometry and repositioned text
"""
import logging
from pathlib import Path
import numpy as np
from PIL import Image, ImageDraw, ImageFont
import cv2
from reportlab.lib.pagesizes import letter, A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

from utils.drawing_state import DrawingState
from config.settings import OUTPUTS_DIR, PDF_DPI

logger = logging.getLogger(__name__)


class PDFCompiler:
    """Compiles final PDF from DraftClear pipeline output"""

    @staticmethod
    def compile_pdf(state: DrawingState, output_name: str = "output") -> str:
        """
        Compile final PDF with healed geometry and repositioned text

        Args:
            state: Final DrawingState from pipeline
            output_name: Name for output PDF

        Returns:
            Path to generated PDF
        """
        logger.info(f"Compiling PDF: {output_name}")

        output_path = OUTPUTS_DIR / f"{output_name}.pdf"

        try:
            # Create canvas
            c = canvas.Canvas(str(output_path), pagesize=letter)
            width, height = letter

            # Draw healed geometry image
            if state.healed_geometry is not None:
                geometry_img_path = OUTPUTS_DIR / f"{output_name}_geometry_temp.png"
                cv2.imwrite(str(geometry_img_path), state.healed_geometry)

                # Scale image to fit page
                c.drawString(50, height - 50, f"DraftClear - Processed Drawing ({output_name})")
                c.drawImage(str(geometry_img_path), 50, height - 500, width=500, height=400)

            # Add repositioned text labels
            if state.new_coordinates:
                y_pos = height - 550
                c.drawString(50, y_pos, "Repositioned Text Labels:")
                y_pos -= 20

                for i, text_box in enumerate(state.new_coordinates):
                    label = f"{i+1}. Position: ({text_box.x:.1f}, {text_box.y:.1f}) | " \
                            f"Size: {text_box.w:.1f}x{text_box.h:.1f} | Confidence: {text_box.confidence:.2f}"
                    c.drawString(70, y_pos, label)
                    y_pos -= 15
                    if y_pos < 50:
                        c.showPage()
                        y_pos = height - 50

            # Add metadata
            c.drawString(50, 30, f"Generated by DraftClear | Iterations: {state.iteration} | Collisions: {state.collision_count}")

            c.save()
            logger.info(f"PDF saved: {output_path}")
            return str(output_path)

        except Exception as e:
            logger.error(f"PDF compilation error: {e}")
            return None

    @staticmethod
    def create_comparison_report(state: DrawingState, output_name: str = "comparison") -> str:
        """
        Create side-by-side comparison report (before/after)

        Args:
            state: Final DrawingState
            output_name: Name for output

        Returns:
            Path to comparison image
        """
        logger.info("Creating comparison report")

        try:
            # Load images
            original = state.original_image
            healed = state.healed_geometry

            if original is None or healed is None:
                logger.warning("Missing images for comparison")
                return None

            # Create side-by-side image
            h, w = original.shape[:2]
            comparison = np.zeros((h, w * 2 + 20, 3), dtype=np.uint8)
            comparison[:, :w] = original
            comparison[:, w+20:] = healed

            # Add labels
            cv2.putText(comparison, "ORIGINAL", (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (0, 255, 0), 2)
            cv2.putText(comparison, "HEALED", (w + 40, 40), cv2.FONT_HERSHEY_SIMPLEX, 1.5, (0, 255, 0), 2)

            # Save
            output_path = OUTPUTS_DIR / f"{output_name}_comparison.png"
            cv2.imwrite(str(output_path), comparison)
            logger.info(f"Comparison saved: {output_path}")

            return str(output_path)

        except Exception as e:
            logger.error(f"Comparison creation error: {e}")
            return None
